### PR TITLE
SystemUI: Introduce user interface for Alert Sliders

### PR DESCRIPTION
**Pull request by Keertesh19**

### CODE REVIEW

**Comment by Maitreya29** [comment]
https://github.com/ProjectRadiant/frameworks_base/pull/8/files#diff-3a1b41648889c95f31c8cbc2c5914ee0f33b7ebc0c1d23cc17a26798c75d6fcaR1

why new line here?

**Review by Maitreya29 — CHANGES_REQUESTED** [review]
Nuke first line on top of Settings.java and rebase and PR again

**Comment by Keertesh19** [comment]
Okay wait

**Review by Maitreya29 — APPROVED** [review]
Fine now, thank you.

**Pull request merged**
