### PR TITLE
PixelPropsUtils: Spoof Pixel 2 for GMS

### PR DESCRIPTION
**Pull request by AtomicXZ**
* fixes safetynet

### CODE REVIEW

**Comment by Maitreya29** [comment]
Pubg 2000 fps with this commit?

**Comment by geek0609** [comment]
@Maitreya29 Yes pubg bgmi good fps 👍

**Comment by Maitreya29** [comment]
Soja ashwin

**Comment by geek0609** [comment]
@Maitreya29 Ok bhai 👍

**Pull request merged**
